import {
  PhoneIncoming,
  PhoneOutgoing,
  PhoneMissed,
  PhoneOff,
  Voicemail,
  UserCheck,
  UserX,
  Radio,
  CheckCircle2,
} from 'lucide-react';

export const EVENT_CATALOG = [
  {
    id: 'call.inbound.started',
    labelKey: 'events.callInboundStarted',
    descKey: 'events.callInboundStartedDesc',
    icon: PhoneIncoming,
    color: 'text-emerald-600',
    bg: 'bg-emerald-50 dark:bg-emerald-950/30',
    border: 'border-emerald-200 dark:border-emerald-800',
  },
  {
    id: 'call.outbound.started',
    labelKey: 'events.callOutboundStarted',
    descKey: 'events.callOutboundStartedDesc',
    icon: PhoneOutgoing,
    color: 'text-blue-600',
    bg: 'bg-blue-50 dark:bg-blue-950/30',
    border: 'border-blue-200 dark:border-blue-800',
  },
  {
    id: 'call.answered',
    labelKey: 'events.callAnswered',
    descKey: 'events.callAnsweredDesc',
    icon: CheckCircle2,
    color: 'text-teal-600',
    bg: 'bg-teal-50 dark:bg-teal-950/30',
    border: 'border-teal-200 dark:border-teal-800',
  },
  {
    id: 'call.ended',
    labelKey: 'events.callEnded',
    descKey: 'events.callEndedDesc',
    icon: PhoneOff,
    color: 'text-slate-600',
    bg: 'bg-slate-50 dark:bg-slate-950/30',
    border: 'border-slate-200 dark:border-slate-800',
  },
  {
    id: 'call.missed',
    labelKey: 'events.callMissed',
    descKey: 'events.callMissedDesc',
    icon: PhoneMissed,
    color: 'text-red-600',
    bg: 'bg-red-50 dark:bg-red-950/30',
    border: 'border-red-200 dark:border-red-800',
  },
  {
    id: 'extension.registered',
    labelKey: 'events.extRegistered',
    descKey: 'events.extRegisteredDesc',
    icon: UserCheck,
    color: 'text-violet-600',
    bg: 'bg-violet-50 dark:bg-violet-950/30',
    border: 'border-violet-200 dark:border-violet-800',
  },
  {
    id: 'extension.unregistered',
    labelKey: 'events.extUnregistered',
    descKey: 'events.extUnregisteredDesc',
    icon: UserX,
    color: 'text-orange-600',
    bg: 'bg-orange-50 dark:bg-orange-950/30',
    border: 'border-orange-200 dark:border-orange-800',
  },
  {
    id: 'voicemail.received',
    labelKey: 'events.voicemailReceived',
    descKey: 'events.voicemailReceivedDesc',
    icon: Voicemail,
    color: 'text-purple-600',
    bg: 'bg-purple-50 dark:bg-purple-950/30',
    border: 'border-purple-200 dark:border-purple-800',
  },
  {
    id: 'trunk.status.changed',
    labelKey: 'events.trunkStatusChanged',
    descKey: 'events.trunkStatusChangedDesc',
    icon: Radio,
    color: 'text-amber-600',
    bg: 'bg-amber-50 dark:bg-amber-950/30',
    border: 'border-amber-200 dark:border-amber-800',
  },
] as const;

export type EventId = (typeof EVENT_CATALOG)[number]['id'];
